sudo: required
services:
  # Tell Travis that required service should be pre-installed on travis instance
  - docker

env:
  global:
    # Determine the current commit SHA
    - SHA=$(git rev-parse HEAD)

    # Does not display any prompts that require user input (press Y/N dialog etc.)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Decrypt a file with cloud credentials
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Download and install Google Cloud SDK CLI on Travis instance every time we run travis build
  - curl https://sdk.cloud.google.com | bash > /dev/null;

  - source $HOME/google-cloud-sdk/path.bash.inc

  # Install and update kubectl in our travis env
  - gcloud components update kubectl

  # Use decrypted sevice-account.json with credentials
  - gcloud auth activate-service-account --key-file service-account.json

  # Where "multi-k8s-304015" is generated ID by google. Can be found in Google cloud dash -> Kubernetes Engine -> cluster -> project
  - gcloud config set project multi-k8s-304015

  # Specify a compute zone: Google cloud dash -> Kubernetes Engine -> cluster -> location
  - gcloud config set compute/zone europe-north1-a

  # Name of a cluster
  - gcloud container clusters get-credentials multi-cluster

  # Log in to the Docker CLI. Credentials are specified in environment variables in Travis CI (Travis.com -> your project -> Settings)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build the test version of multi-client image and run tests inside of it
  - docker build -t calliduss/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests from previously created build
  - docker run -e CI=true calliduss/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master